
export const metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default async function LoginLayout({ children }) {
  return (
    <div className="h-full">
      {children}
    </div>
  );
}
