import { Suspense } from "react";
import Loading from "../blog/loading";

export const metadata = {
  title: "Register",
  description: "Generated by create next app",
};

export default async function RegisterLayout({ children }) {
  return (
    <div className="h-full flex justify-center items-center">
      <Suspense fallback={<Loading />}>{children}</Suspense>
    </div>
  );
}
